spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(9ErSvYBu5deFXj+OjAx6RCpeT8eVq26I1bofxrN3o7nwo4w0gL8u3xra4FrijGSHp+eDgx77pT0Kca4+A5GO9JYBJeIwrCAIm5GqbEzTf9ZMpezUiZYwHR3J7YFD3SkS)
    username: ENC(LF3grdejR4h2BDQyB1yFzaMyzXgEqXnep+NQMq6iGzOiG7buPf23O24GEmbNlwbk)
    password: ENC(LF3grdejR4h2BDQyB1yFzaMyzXgEqXnep+NQMq6iGzOiG7buPf23O24GEmbNlwbk)

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: ENC(mlamO52Aq4UTHfJneP50K+PpZ+qpj0acTf25ATziku7vUzUYYAEJ34rUXYklMCW8hpVPBB25xe7jtxK7XtBzNg==)
    port: 6379
    password: ENC(5cCIhYh6AIENQIfr7verUrRMwxL8T152nOE9K2Rz1BkxX7Uj2xNXQcUCDsHtvB4v)


jasypt:
  encryptor:
    key: ${JASYPT_KEY}

logging:
  level:
    root: info
    org.hibernate.type: trace
    org.hibernate.SQL: debug

jwt:
  key: ENC(SFzMRlkdgp5cdknU5Jbq6q3YCh3i4UJKCz0gJsgpG2zQnOfqTRlwbQcDfVlN3VNP8ID25ATJEzy60Jd+WwAgislVNlSH0rsB38QfmD5XPhb0O25F1wsYmkC7rFn+Uij9XYkAKM05ATT6cHXy0TKiOxeCseeKpaIAorieYjUS+9Wmet4YOOUyIMnCZix0zvx7)


urban-nest:
  image:
    max-cnt: 20
    max-size: 10485760 #1024*1024*10 => 10MB
    save-path:
      local: ENC(bZhLo4VlQc6zytBWxWrn3bPRmA6RW4o1GJ7lc8vxPGbzvOixVDC/jFh4KJtBM/R7x8vD3zyA7zWhQf+Le0UaeSgvvhNKb2K0oGHepBZvShJ1eQDahabuz3RcqxChOMzL)

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

kakao:
  client:
    id: 419cc86098a7b157b129c35609e3fc5a
    secret: wbgzBDDvIg84Gv3NZmjZn07gsQDoJdeB
